"""Signal-change event detection: compares the candidate snapshot against the
previous production snapshot and emits typed, deterministic events.

Every event carries prev/current values and magnitude in a JSON detail blob;
nothing is generated by an LLM. Written to daily_change_events
(snapshot_date, key, event_type, detail) — consolidation happens at query
time (first seen / last seen / count) so repeats never spam the tape.
"""
import json

PREM_THRESHOLDS = [-30, -15, 15, 30]
MOVE_1D = 3.0
DISCOUNT_DELTA = 5.0


def _ev(events, snap, key, etype, prev=None, cur=None, magnitude=None,
        confidence='ok', note=''):
    events.append((snap, key, etype, json.dumps(
        dict(prev=prev, cur=cur, magnitude=magnitude,
             confidence=confidence, note=note))))


def detect_events(cur_rows, prev_rows, cur_drill=None, snap=None):
    """cur_rows/prev_rows: {key: screener row dict}. cur_drill: {key: drill}."""
    events = []
    cur_drill = cur_drill or {}
    for k, c in cur_rows.items():
        p = prev_rows.get(k)
        if not p:
            _ev(events, snap, k, 'universe_entry', note='entered the screener universe')
            continue
        # ---- state changes ------------------------------------------------
        for dim in ('momentum_state', 'valuation_state', 'fundamental_state'):
            if c.get(dim) and p.get(dim) and c[dim] != p[dim]:
                _ev(events, snap, k, f'{dim}_change', p[dim], c[dim],
                    note=f'{dim.replace("_", " ")}: {p[dim]} -> {c[dim]}')
        # ---- valuation events --------------------------------------------
        pc, pp = c.get('prem_disc_vs_peers_pct'), p.get('prem_disc_vs_peers_pct')
        if pc is not None and pp is not None:
            for t in PREM_THRESHOLDS:
                if (pp > t) != (pc > t):
                    _ev(events, snap, k, 'peer_discount_threshold', pp, pc, t,
                        note=f'crossed {t:+d}% vs peer median')
            if abs(pc - pp) >= DISCOUNT_DELTA:
                _ev(events, snap, k, 'peer_discount_move', pp, pc,
                    round(pc - pp, 1),
                    note=f'peer discount moved {pc - pp:+.1f}pp')
        hc, hp = c.get('hist_percentile'), p.get('hist_percentile')
        if hc is not None and hp is not None and (hp < 20) != (hc < 20):
            _ev(events, snap, k, 'own_history_extreme', hp, hc,
                confidence=f"coarse (n={c.get('hist_years')})",
                note='own-history percentile crossed 20th')
        # ---- price events -------------------------------------------------
        m1 = c.get('rel_1m_pct')
        dd_c, dd_p = c.get('drawdown_52w_pct'), p.get('drawdown_52w_pct')
        if dd_c is not None and dd_p is not None:
            if dd_c > -0.5 and dd_p <= -0.5:
                _ev(events, snap, k, 'new_52w_high', dd_p, dd_c,
                    note='trading at/near 52-week high')
            if dd_c <= -20 and dd_p > -20:
                _ev(events, snap, k, 'drawdown_threshold', dd_p, dd_c,
                    note='drawdown exceeded 20% from 52w high')
        # ---- fundamental events -------------------------------------------
        for col, label in (('rev_growth_pct', 'revenue growth'),
                           ('margin_chg_pp', 'margin trend'),
                           ('nd_ebitda', 'leverage')):
            cv, pv = c.get(col), p.get(col)
            if cv is not None and pv is not None and cv != pv:
                if col == 'nd_ebitda' and (pv < 3) != (cv < 3):
                    _ev(events, snap, k, 'leverage_threshold', pv, cv,
                        note='ND/EBITDA crossed 3.0x')
                elif col != 'nd_ebitda' and (pv < 0) != (cv < 0):
                    _ev(events, snap, k, f'{col}_sign_change', pv, cv,
                        note=f'{label} changed sign')
        # ---- data-quality events ------------------------------------------
        if c.get('data_quality') != p.get('data_quality'):
            worse = len(c.get('data_quality') or '') > len(p.get('data_quality') or '')
            _ev(events, snap, k,
                'data_quality_new' if worse else 'data_quality_resolved',
                p.get('data_quality'), c.get('data_quality'),
                note='data-quality flags changed')
        # ---- momentum crossover (from drill payload) ----------------------
        d = cur_drill.get(k) or {}
        ema = ((d.get('momentum') or {}).get('ema') or {}).get('ema_20_60') or {}
        ssc = ema.get('sessions_since_cross')
        try:
            ssc = int(ssc) if ssc is not None else None
        except (TypeError, ValueError):
            ssc = None
        if ssc is not None and ssc <= 1:
            _ev(events, snap, k, 'ema_20_60_cross', None, ema.get('state'),
                ema.get('gap_pct'),
                note=f"fresh 20/60 EMA cross -> {ema.get('state')} "
                     f"({ema.get('cross_date')})")
    for k in prev_rows:
        if k not in cur_rows:
            _ev(events, snap, k, 'universe_exit', note='left the screener universe')
    return events


def detect_and_store(db, snap):
    """Replaces detect_changes: richer event engine against the DB."""
    prev = db.fetchall(
        'SELECT max(snapshot_date) FROM feat_screener WHERE snapshot_date < ?'
        .replace('?', db.ph), [snap])[0][0]
    if not prev:
        return 0
    cur = {r[0]: json.loads(r[1]) for r in db.fetchall(
        f'SELECT key, payload FROM feat_screener WHERE snapshot_date = {db.ph}', [snap])}
    old = {r[0]: json.loads(r[1]) for r in db.fetchall(
        f'SELECT key, payload FROM feat_screener WHERE snapshot_date = {db.ph}', [prev])}
    drill = {}
    row = db.fetchall(f'SELECT payload FROM app_payload WHERE snapshot_date = {db.ph}',
                      [snap])
    if row:
        drill = json.loads(row[0][0]).get('drill', {})
    events = detect_events(cur, old, drill, str(snap))
    return db.upsert('daily_change_events',
                     ['snapshot_date', 'key', 'event_type', 'detail'],
                     events, ['snapshot_date', 'key', 'event_type'])
