import json
import pandas as pd
import streamlit as st
from components.data import payload, q, ph
from components.ui import df_show, group_header, style_table

st.title('Signal Change Tape')
st.caption('What changed since the previous successful snapshot — typed, '
           'deterministic events with previous/current values. Repeats are '
           'consolidated (first seen / last seen / count), never re-spammed. '
           'No event is a recommendation.')

D = payload()
scr = {r['key']: r for r in D['screener']}
roles = {}
for r in D['close_rows']:
    roles.setdefault(r['key'], r['role'])

CATEGORY = {
    'momentum_state_change': 'Momentum', 'ema_20_60_cross': 'Momentum',
    'valuation_state_change': 'Valuation', 'peer_discount_threshold': 'Valuation',
    'peer_discount_move': 'Valuation', 'own_history_extreme': 'Valuation',
    'fundamental_state_change': 'Fundamentals',
    'rev_growth_pct_sign_change': 'Fundamentals',
    'margin_chg_pp_sign_change': 'Fundamentals',
    'leverage_threshold': 'Fundamentals',
    'new_52w_high': 'Price', 'drawdown_threshold': 'Price',
    'large_price_move': 'Price',
    'data_quality_new': 'Data', 'data_quality_resolved': 'Data',
    'universe_entry': 'Data', 'universe_exit': 'Data',
    'classification_change': 'Data', 'new_security': 'Data',
}

rows = q("""SELECT key, event_type, detail,
                   min(snapshot_date), max(snapshot_date), count(*)
            FROM daily_change_events
            GROUP BY key, event_type, detail
            ORDER BY max(snapshot_date) DESC, key""")
if not rows:
    st.info('No events yet — the tape fills as daily snapshots accumulate. '
            'Each weekday refresh diffs the new snapshot against the previous '
            'one across momentum, valuation, fundamental, price and '
            'data-quality dimensions.')
    st.stop()

recs = []
for k, etype, detail, first, last, n in rows:
    try:
        d = json.loads(detail)
    except Exception:
        d = {'note': detail}
    wl = q(f'SELECT count(*) FROM watchlist_members WHERE key = {ph()}', [k])[0][0]
    recs.append({
        'Company': (D['names'].get(k, k)), 'Key': k,
        'Category': CATEGORY.get(etype, 'Other'), 'Event': etype.replace('_', ' '),
        'Previous': d.get('prev'), 'Current': d.get('cur'),
        'Magnitude': d.get('magnitude'), 'Explanation': d.get('note', ''),
        'Confidence': d.get('confidence', 'ok'),
        'First seen': str(first), 'Last seen': str(last), 'Count': n,
        'Role': roles.get(k, '?'), 'Watchlisted': bool(wl),
        'Subgroup': scr.get(k, {}).get('subgroup', '')})
df = pd.DataFrame(recs)

c1, c2, c3, c4 = st.columns(4)
cat = c1.multiselect('Category', sorted(df['Category'].unique()))
sub = c2.multiselect('Subgroup', sorted(x for x in df['Subgroup'].unique() if x))
role = c3.selectbox('Universe', ['All', 'Coverage only', 'Peers only'])
wl_only = c4.checkbox('Watchlist only')
f = df.copy()
if cat: f = f[f['Category'].isin(cat)]
if sub: f = f[f['Subgroup'].isin(sub)]
if role == 'Coverage only': f = f[f['Role'] == 'coverage']
if role == 'Peers only': f = f[f['Role'] == 'peer']
if wl_only: f = f[f['Watchlisted']]

group_header(f'{len(f)} consolidated events')
show = f[['Company', 'Key', 'Category', 'Event', 'Previous', 'Current',
          'Magnitude', 'Explanation', 'Confidence', 'First seen', 'Last seen',
          'Count']]
df_show(show, height=560)
st.download_button('Export CSV', show.to_csv(index=False), 'signal_change_tape.csv')
st.caption('Open a company on the Drill-Down page (select it there by name) '
           'for the evidence behind any event. Events are generated by '
           'src/screening/events.py from stored snapshot fields — '
           'deterministic, auditable, LLM-free.')
